//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceMonitor.ServiceReferenceSemVITICw {
    using System.Runtime.Serialization;
    using System;
    using Models;

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClientGridViewModel", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ClientGridViewModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string PhoneNumber {
            get {
                return this.PhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumberField, value) != true)) {
                    this.PhoneNumberField = value;
                    this.RaisePropertyChanged("PhoneNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceSemVITICw.TechnologieInternetoweCwSoap")]
    public interface TechnologieInternetoweCwSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        ServiceMonitor.ServiceReferenceSemVITICw.HelloWorldResponse HelloWorld(ServiceMonitor.ServiceReferenceSemVITICw.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceMonitor.ServiceReferenceSemVITICw.HelloWorldResponse> HelloWorldAsync(ServiceMonitor.ServiceReferenceSemVITICw.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name model from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckClient2", ReplyAction="*")]
        ServiceMonitor.ServiceReferenceSemVITICw.CheckClient2Response CheckClient2(ServiceMonitor.ServiceReferenceSemVITICw.CheckClient2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckClient2", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceMonitor.ServiceReferenceSemVITICw.CheckClient2Response> CheckClient2Async(ServiceMonitor.ServiceReferenceSemVITICw.CheckClient2Request request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public ServiceMonitor.ServiceReferenceSemVITICw.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(ServiceMonitor.ServiceReferenceSemVITICw.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceMonitor.ServiceReferenceSemVITICw.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(ServiceMonitor.ServiceReferenceSemVITICw.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckClient2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckClient2", Namespace="http://tempuri.org/", Order=0)]
        public ServiceMonitor.ServiceReferenceSemVITICw.CheckClient2RequestBody Body;
        
        public CheckClient2Request() {
        }
        
        public CheckClient2Request(ServiceMonitor.ServiceReferenceSemVITICw.CheckClient2RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckClient2RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceMonitor.ServiceReferenceSemVITICw.ClientGridViewModel model;
        
        public CheckClient2RequestBody() {
        }
        
        public CheckClient2RequestBody(ServiceMonitor.ServiceReferenceSemVITICw.ClientGridViewModel model) {
            this.model = model;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckClient2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckClient2Response", Namespace="http://tempuri.org/", Order=0)]
        public ServiceMonitor.ServiceReferenceSemVITICw.CheckClient2ResponseBody Body;
        
        public CheckClient2Response() {
        }
        
        public CheckClient2Response(ServiceMonitor.ServiceReferenceSemVITICw.CheckClient2ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckClient2ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceMonitor.ServiceReferenceSemVITICw.ClientGridViewModel CheckClient2Result;
        
        public CheckClient2ResponseBody() {
        }
        
        public CheckClient2ResponseBody(ServiceMonitor.ServiceReferenceSemVITICw.ClientGridViewModel CheckClient2Result) {
            this.CheckClient2Result = CheckClient2Result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TechnologieInternetoweCwSoapChannel : ServiceMonitor.ServiceReferenceSemVITICw.TechnologieInternetoweCwSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TechnologieInternetoweCwSoapClient : System.ServiceModel.ClientBase<ServiceMonitor.ServiceReferenceSemVITICw.TechnologieInternetoweCwSoap>, ServiceMonitor.ServiceReferenceSemVITICw.TechnologieInternetoweCwSoap {
        
        public TechnologieInternetoweCwSoapClient() {
        }
        
        public TechnologieInternetoweCwSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TechnologieInternetoweCwSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TechnologieInternetoweCwSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TechnologieInternetoweCwSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceMonitor.ServiceReferenceSemVITICw.HelloWorldResponse ServiceMonitor.ServiceReferenceSemVITICw.TechnologieInternetoweCwSoap.HelloWorld(ServiceMonitor.ServiceReferenceSemVITICw.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            ServiceMonitor.ServiceReferenceSemVITICw.HelloWorldRequest inValue = new ServiceMonitor.ServiceReferenceSemVITICw.HelloWorldRequest();
            inValue.Body = new ServiceMonitor.ServiceReferenceSemVITICw.HelloWorldRequestBody();
            ServiceMonitor.ServiceReferenceSemVITICw.HelloWorldResponse retVal = ((ServiceMonitor.ServiceReferenceSemVITICw.TechnologieInternetoweCwSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceMonitor.ServiceReferenceSemVITICw.HelloWorldResponse> ServiceMonitor.ServiceReferenceSemVITICw.TechnologieInternetoweCwSoap.HelloWorldAsync(ServiceMonitor.ServiceReferenceSemVITICw.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceMonitor.ServiceReferenceSemVITICw.HelloWorldResponse> HelloWorldAsync() {
            ServiceMonitor.ServiceReferenceSemVITICw.HelloWorldRequest inValue = new ServiceMonitor.ServiceReferenceSemVITICw.HelloWorldRequest();
            inValue.Body = new ServiceMonitor.ServiceReferenceSemVITICw.HelloWorldRequestBody();
            return ((ServiceMonitor.ServiceReferenceSemVITICw.TechnologieInternetoweCwSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceMonitor.ServiceReferenceSemVITICw.CheckClient2Response ServiceMonitor.ServiceReferenceSemVITICw.TechnologieInternetoweCwSoap.CheckClient2(ServiceMonitor.ServiceReferenceSemVITICw.CheckClient2Request request) {
            return base.Channel.CheckClient2(request);
        }
        
        public ServiceMonitor.ServiceReferenceSemVITICw.ClientGridViewModel CheckClient2(ServiceMonitor.ServiceReferenceSemVITICw.ClientGridViewModel model) {
            ServiceMonitor.ServiceReferenceSemVITICw.CheckClient2Request inValue = new ServiceMonitor.ServiceReferenceSemVITICw.CheckClient2Request();
            inValue.Body = new ServiceMonitor.ServiceReferenceSemVITICw.CheckClient2RequestBody();
            inValue.Body.model = model;
            ServiceMonitor.ServiceReferenceSemVITICw.CheckClient2Response retVal = ((ServiceMonitor.ServiceReferenceSemVITICw.TechnologieInternetoweCwSoap)(this)).CheckClient2(inValue);
            return retVal.Body.CheckClient2Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceMonitor.ServiceReferenceSemVITICw.CheckClient2Response> ServiceMonitor.ServiceReferenceSemVITICw.TechnologieInternetoweCwSoap.CheckClient2Async(ServiceMonitor.ServiceReferenceSemVITICw.CheckClient2Request request) {
            return base.Channel.CheckClient2Async(request);
        }
        
        public System.Threading.Tasks.Task<ServiceMonitor.ServiceReferenceSemVITICw.CheckClient2Response> CheckClient2Async(ServiceMonitor.ServiceReferenceSemVITICw.ClientGridViewModel model) {
            ServiceMonitor.ServiceReferenceSemVITICw.CheckClient2Request inValue = new ServiceMonitor.ServiceReferenceSemVITICw.CheckClient2Request();
            inValue.Body = new ServiceMonitor.ServiceReferenceSemVITICw.CheckClient2RequestBody();
            inValue.Body.model = model;
            return ((ServiceMonitor.ServiceReferenceSemVITICw.TechnologieInternetoweCwSoap)(this)).CheckClient2Async(inValue);
        }
    }
}
