//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceMonitor
{
    using System;
    using System.Collections.Generic;
    
    public partial class Addresss
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Addresss()
        {
            this.Customer = new HashSet<Customer>();
            this.Performer = new HashSet<Performer>();
            this.PODGiK = new HashSet<PODGiK>();
        }
    
        public int Id { get; set; }
        public int IdVoivodeship { get; set; }
        public int IdCounty { get; set; }
        public int IdCommune { get; set; }
        public int IdLocality { get; set; }
        public string Street { get; set; }
        public string HouseNumber { get; set; }
        public string PlotNumber { get; set; }
    
        public virtual Commune Commune { get; set; }
        public virtual County County { get; set; }
        public virtual Locality Locality { get; set; }
        public virtual Voivodeship Voivodeship { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customer> Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Performer> Performer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PODGiK> PODGiK { get; set; }
    }
}
