//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceMonitor
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SDA_EndProjContext : DbContext
    {
        public SDA_EndProjContext()
            : base("name=SDA_EndProjContext1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Addresss> Addresss { get; set; }
        public virtual DbSet<ChangeStageWork> ChangeStageWork { get; set; }
        public virtual DbSet<Commune> Commune { get; set; }
        public virtual DbSet<County> County { get; set; }
        public virtual DbSet<Customer> Customer { get; set; }
        public virtual DbSet<GeodeticPoint> GeodeticPoint { get; set; }
        public virtual DbSet<Locality> Locality { get; set; }
        public virtual DbSet<Performer> Performer { get; set; }
        public virtual DbSet<PODGiK> PODGiK { get; set; }
        public virtual DbSet<Servicee> Servicee { get; set; }
        public virtual DbSet<StateOfPoint> StateOfPoint { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TypeService> TypeService { get; set; }
        public virtual DbSet<Voivodeship> Voivodeship { get; set; }
        public virtual DbSet<WorkStage> WorkStage { get; set; }
    }
}
