//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceMonitor
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeodeticPoint
    {
        public int Id { get; set; }
        public string Number { get; set; }
        public int IdAddress { get; set; }
        public double X { get; set; }
        public double Y { get; set; }
        public Nullable<int> IdState { get; set; }
    
        public virtual StateOfPoint StateOfPoint { get; set; }
    }
}
