//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceMonitor
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SDA_EndProjEntitiesLocalHp : DbContext
    {
        public SDA_EndProjEntitiesLocalHp()
            : base("name=SDA_EndProjEntitiesLocalHp")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Addresss> Addressses { get; set; }
        public virtual DbSet<ChangeStageWork> ChangeStageWorks { get; set; }
        public virtual DbSet<Commune> Communes { get; set; }
        public virtual DbSet<County> Counties { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<GeodeticPoint> GeodeticPoints { get; set; }
        public virtual DbSet<Locality> Localities { get; set; }
        public virtual DbSet<Performer> Performers { get; set; }
        public virtual DbSet<PODGiK> PODGiKs { get; set; }
        public virtual DbSet<Servicee> Servicees { get; set; }
        public virtual DbSet<StateOfPoint> StateOfPoints { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TypeService> TypeServices { get; set; }
        public virtual DbSet<Voivodeship> Voivodeships { get; set; }
        public virtual DbSet<WorkStage> WorkStages { get; set; }
    }
}
