//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceMonitor
{
    using System;
    using System.Collections.Generic;
    
    public partial class Servicee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Servicee()
        {
            this.ChangeStageWorks = new HashSet<ChangeStageWork>();
        }
    
        public int Id { get; set; }
        public int IdPerformer { get; set; }
        public int IdCustomer { get; set; }
        public int IdType { get; set; }
        public double Price { get; set; }
        public string Descriptionn { get; set; }
        public int IdPODGiK { get; set; }
        public int IdAddress { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChangeStageWork> ChangeStageWorks { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Performer Performer { get; set; }
        public virtual PODGiK PODGiK { get; set; }
        public virtual TypeService TypeService { get; set; }
    }
}
